# Generated by Django 5.2.1 on 2025-06-24 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('is_canceld', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='courses.coursemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentmodel')),
            ],
        ),
    ]
