# Generated by Django 5.2.1 on 2025-06-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentmodel',
            old_name='is_canceld',
            new_name='is_canceled',
        ),
        migrations.AlterField(
            model_name='enrollmentmodel',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
